trigger:
  - main   # Runs pipeline when code is pushed to main branch

pool:
  vmImage: 'ubuntu-latest'   # Agent pool (Microsoft-hosted Ubuntu VM)

stages:
- stage: Build
  displayName: "Build Stage"
  jobs:
  - job: BuildJob
    displayName: "Build the application"
    steps:
      - script: echo "Restoring dependencies..."
        displayName: "Restore Dependencies"

      - script: echo "Building the project..."
        displayName: "Build Project"

      - script: echo "Running tests..."
        displayName: "Run Unit Tests"

      - script: echo "Packaging application..."
        displayName: "Package Application"

- stage: PreProduction
  displayName: "PreProduction Stage"
  dependsOn: Build   # Ensures Build runs before PreProduction
  jobs:
  - job: PreProdJob
    displayName: "Deploy to PreProduction"
    steps:
      - script: echo "Deploying to PreProduction environment..."
        displayName: "Deploy"

      - script: echo "Running sanity checks in PreProduction..."
        displayName: "Run PreProduction Tests"
