trigger:
- main   # pipeline runs when code is pushed to main branch

pool:
  vmImage: 'ubuntu-latest'

stages:
# -------------------------
# 1. BUILD STAGE
# -------------------------
- stage: Build
  displayName: "Build Stage"
  jobs:
  - job: BuildJob
    displayName: "Build Application"
    steps:
      - script: echo "Building the application..."
        displayName: "Run build steps"

# -------------------------
# 2. PRE-PRODUCTION STAGE
# -------------------------
- stage: PreProduction
  displayName: "Pre-Production Stage"
  dependsOn: Build
  jobs:
  - job: DeployPreProd
    displayName: "Deploy to Pre-Production"
    steps:
      - script: echo "Deploying to Pre-Production environment..."
        displayName: "Deploy application"

# -------------------------
# 3. PRODUCTION STAGE
# -------------------------
- stage: Production
  displayName: "Production Stage"
  dependsOn: PreProduction
  condition: succeeded()   # only runs if PreProd succeeds
  jobs:
  - deployment: DeployProd
    displayName: "Deploy to Production"
    environment: "production"   # requires manual approval in Azure DevOps Environments
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo "Deploying to Production environment..."
              displayName: "Deploy application to Prod"
